# Generated by Django 4.2.7 on 2024-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='noone', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
