# Generated by Django 4.1.7 on 2024-08-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shopcustomer'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='prescription',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.customerprescription'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shop'),
        ),
        migrations.AddField(
            model_name='customerprescription',
            name='customer',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shopcustomer'),
        ),
        migrations.AddField(
            model_name='customerprescription',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shop'),
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.state'),
        ),
        migrations.AlterUniqueTogether(
            name='shoptaxdetails',
            unique_together={('id', 'shop_id')},
        ),
        migrations.AlterUniqueTogether(
            name='shopcustomer',
            unique_together={('id', 'shop_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('id', 'shop_id')},
        ),
        migrations.AlterUniqueTogether(
            name='customerprescription',
            unique_together={('id', 'shop_id')},
        ),
    ]
