# Generated by Django 4.1.7 on 2024-10-25 10:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='DateCreatedUtc',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 25, 10, 55, 46, 787633, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='DateModifiedUtc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoptaxdetails',
            name='DateCreatedUtc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoptaxdetails',
            name='DateModifiedUtc',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoptaxdetails',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoptaxdetails',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
