# Generated by Django 4.1.7 on 2024-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
