# Generated by Django 4.1.7 on 2024-12-16 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optics', '0004_shop_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
