# Generated by Django 4.1.7 on 2024-12-16 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optics', '0005_remove_shop_owner_shop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
