# Generated by Django 4.1.7 on 2024-09-07 06:12

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('optics', '0002_initial'),
        ('customer_prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frame_type', models.CharField(max_length=255)),
                ('frame_details', models.TextField()),
                ('frame_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glass_detail', models.TextField()),
                ('glass_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_lens_detail', models.TextField()),
                ('contact_lens_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField()),
                ('extra_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_status', models.CharField(max_length=20)),
                ('customer', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.shopcustomer')),
                ('prescription', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_prescriptions.customerprescription')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shop')),
            ],
            options={
                'unique_together': {('id', 'shop_id')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
