# Generated by Django 4.1.7 on 2024-09-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='contact_lens_detail',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='contact_lens_price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='extra_charges',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='frame_details',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='frame_price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='frame_type',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='glass_detail',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='glass_price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_amount',
        ),
    ]
