# Generated by Django 4.1.7 on 2024-09-07 06:12

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('optics', '0002_initial'),
        ('customer_prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprescription',
            name='customer',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.shopcustomer'),
        ),
        migrations.AddField(
            model_name='customerprescription',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='customerprescription',
            unique_together={('id', 'shop_id')},
        ),
    ]
