# Generated by Django 4.1.7 on 2024-09-07 06:12

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optics.shop')),
            ],
            options={
                'unique_together': {('id', 'shop_id')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
