# Generated by Django 4.1.7 on 2024-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0007_shop_branch_identifier'),
        ('users', '0002_user_datecreatedutc_user_datemodifiedutc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='users', to='optics.shop'),
        ),
    ]
